import { Uri } from "./components/Constants_";

export const dataSong = [
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[0],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[1],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[0],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[1],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[0],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[1],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[0],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[1],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[0],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[1],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[0],
    yearOfPublish: 2020,
  },
  {
    title: "this is the title",
    duration: "4:27",
    artist: "this is the artist",
    views: "12k",
    inFavorites: false,
    poster: Uri.images[1],
    yearOfPublish: 2020,
  },
];
